### INPUT

# ckpt_path     : ckpts_test/orig_nan_255000.pth
# ckpt_path                   :  ckpts_test/degae_ablation_255000.pth
ckpt_path                   :  out/degae_targetRef_origRgbFeat_WeightSum_preBPN_woProcRgbSample_RevisedStepDecay40k-2_LatentLoss1e0__tar__full__pre__3_3_3__views_attn__l1/model_010000.pth
# ckpt_path                   : ckpts_test/DegAE_AllCondRenderer_preBPN_weightSumFilter_perImg_ftEmbed_embedLoss1e3_200000.pth
distributed                 : False
no_load_opt                 : True
no_load_scheduler           : True
include_target              : True
##
views_attn                  : True
kernel_size                 : [3, 3]
pre_net                     : True
noise_feat                  : False
rgb_weights                 : True

##
degae_feat                  : True
weightsum_filtered          : True
bpn_prenet                  : True
bpn_per_img                 : True
exclude_proc_rgb            : True
cond_renderer               : False #True
basis_dim                   : 64

## dataset
eval_dataset : llff_test
eval_scenes  : fern

### TESTING
chunk_size    : 2048
render_stride : 4

## ADDITIONAL
same          : True
num_source_views : 8

 eval_images : True
 eval_rays   : True
 rerun       : True

process_output : True

local_rank : 0