### INPUT
expname                     : test
render_stride               : 1  # used in evaluation
distributed                 : False

## dataset
train_dataset               : llff
eval_dataset                : llff_test
eval_scenes                 : [fern, orchids, flower, horns, leaves, room, trex, fortress] # [fern, trex, leaves, horns]

### TRAINING
n_iters                     : 255000
N_rand                      : 512
lrate_feature               : 0.001
lrate_mlp                   : 0.0005
lrate_decay_factor          : 0.5
lrate_decay_steps           : 50000
losses                      : [l2, l1, l1_grad, ssim]
losses_weights              : [0,  1,  0,       0]
workers                     : 0

coarse_feat_dim             : 32
fine_feat_dim               : 32
img_size                    : 256
burst_length                : 3
num_source_views            : 3

### TESTING
chunk_size                  : 2048 #2048 # can be bigger depend on the gpu memory

### RENDERING
N_importance                : 64
N_samples                   : 64
inv_uniform                 : True
white_bkgd                  : False

### CONSOLE AND TENSORBOARD
i_img                       : 6000
i_print                     : 100
i_tb                        : 20
i_weights                   : 5000

### additional
eval_mode                   : True
no_load_opt                 : False
no_load_scheduler           : False
sup_clean                   : True

include_target              : False  # set to False if you want to synthesize images rather than denoise the images
eval_gain                    : [20, 16, 8]
std                         : [-3.0, -0.5, -2.0, -0.5]


views_attn                  : True
kernel_size                 : [3, 3]
pre_net                     : True
noise_feat                  : True
rgb_weights                 : True

local_rank                  : 0
